// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: targeting_sessionlog.proto

package com.autohome.adrd.algo.protobuf;

public final class TargetingOperation {
  private TargetingOperation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TargetingInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string tagid = 1;
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    boolean hasTagid();
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    java.lang.String getTagid();
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    com.google.protobuf.ByteString
        getTagidBytes();

    // optional float score = 2;
    /**
     * <code>optional float score = 2;</code>
     *
     * <pre>
     *标签权重
     * </pre>
     */
    boolean hasScore();
    /**
     * <code>optional float score = 2;</code>
     *
     * <pre>
     *标签权重
     * </pre>
     */
    float getScore();
  }
  /**
   * Protobuf type {@code Targeting.TargetingInfo}
   */
  public static final class TargetingInfo extends
      com.google.protobuf.GeneratedMessage
      implements TargetingInfoOrBuilder {
    // Use TargetingInfo.newBuilder() to construct.
    private TargetingInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TargetingInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TargetingInfo defaultInstance;
    public static TargetingInfo getDefaultInstance() {
      return defaultInstance;
    }

    public TargetingInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TargetingInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              tagid_ = input.readBytes();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              score_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.class, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<TargetingInfo> PARSER =
        new com.google.protobuf.AbstractParser<TargetingInfo>() {
      public TargetingInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TargetingInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TargetingInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string tagid = 1;
    public static final int TAGID_FIELD_NUMBER = 1;
    private java.lang.Object tagid_;
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    public boolean hasTagid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    public java.lang.String getTagid() {
      java.lang.Object ref = tagid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tagid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string tagid = 1;</code>
     *
     * <pre>
     *标签
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTagidBytes() {
      java.lang.Object ref = tagid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tagid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional float score = 2;
    public static final int SCORE_FIELD_NUMBER = 2;
    private float score_;
    /**
     * <code>optional float score = 2;</code>
     *
     * <pre>
     *标签权重
     * </pre>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float score = 2;</code>
     *
     * <pre>
     *标签权重
     * </pre>
     */
    public float getScore() {
      return score_;
    }

    private void initFields() {
      tagid_ = "";
      score_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTagidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTagidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Targeting.TargetingInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.class, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder.class);
      }

      // Construct using com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        tagid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfo_descriptor;
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo getDefaultInstanceForType() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.getDefaultInstance();
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo build() {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo buildPartial() {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo result = new com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tagid_ = tagid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo) {
          return mergeFrom((com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo other) {
        if (other == com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.getDefaultInstance()) return this;
        if (other.hasTagid()) {
          bitField0_ |= 0x00000001;
          tagid_ = other.tagid_;
          onChanged();
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string tagid = 1;
      private java.lang.Object tagid_ = "";
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public boolean hasTagid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public java.lang.String getTagid() {
        java.lang.Object ref = tagid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          tagid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTagidBytes() {
        java.lang.Object ref = tagid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tagid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public Builder setTagid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tagid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public Builder clearTagid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tagid_ = getDefaultInstance().getTagid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string tagid = 1;</code>
       *
       * <pre>
       *标签
       * </pre>
       */
      public Builder setTagidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tagid_ = value;
        onChanged();
        return this;
      }

      // optional float score = 2;
      private float score_ ;
      /**
       * <code>optional float score = 2;</code>
       *
       * <pre>
       *标签权重
       * </pre>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float score = 2;</code>
       *
       * <pre>
       *标签权重
       * </pre>
       */
      public float getScore() {
        return score_;
      }
      /**
       * <code>optional float score = 2;</code>
       *
       * <pre>
       *标签权重
       * </pre>
       */
      public Builder setScore(float value) {
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float score = 2;</code>
       *
       * <pre>
       *标签权重
       * </pre>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Targeting.TargetingInfo)
    }

    static {
      defaultInstance = new TargetingInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Targeting.TargetingInfo)
  }

  public interface TargetingInfoListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Targeting.TargetingInfo tag = 1;
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> 
        getTagList();
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo getTag(int index);
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    int getTagCount();
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    java.util.List<? extends com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder> 
        getTagOrBuilderList();
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder getTagOrBuilder(
        int index);

    // optional string cookietime = 2;
    /**
     * <code>optional string cookietime = 2;</code>
     */
    boolean hasCookietime();
    /**
     * <code>optional string cookietime = 2;</code>
     */
    java.lang.String getCookietime();
    /**
     * <code>optional string cookietime = 2;</code>
     */
    com.google.protobuf.ByteString
        getCookietimeBytes();
  }
  /**
   * Protobuf type {@code Targeting.TargetingInfoList}
   */
  public static final class TargetingInfoList extends
      com.google.protobuf.GeneratedMessage
      implements TargetingInfoListOrBuilder {
    // Use TargetingInfoList.newBuilder() to construct.
    private TargetingInfoList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TargetingInfoList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TargetingInfoList defaultInstance;
    public static TargetingInfoList getDefaultInstance() {
      return defaultInstance;
    }

    public TargetingInfoList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TargetingInfoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                tag_ = new java.util.ArrayList<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              tag_.add(input.readMessage(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              cookietime_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.class, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.Builder.class);
    }

    public static com.google.protobuf.Parser<TargetingInfoList> PARSER =
        new com.google.protobuf.AbstractParser<TargetingInfoList>() {
      public TargetingInfoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TargetingInfoList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TargetingInfoList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .Targeting.TargetingInfo tag = 1;
    public static final int TAG_FIELD_NUMBER = 1;
    private java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> tag_;
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    public java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> getTagList() {
      return tag_;
    }
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    public java.util.List<? extends com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
     */
    public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }

    // optional string cookietime = 2;
    public static final int COOKIETIME_FIELD_NUMBER = 2;
    private java.lang.Object cookietime_;
    /**
     * <code>optional string cookietime = 2;</code>
     */
    public boolean hasCookietime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string cookietime = 2;</code>
     */
    public java.lang.String getCookietime() {
      java.lang.Object ref = cookietime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cookietime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cookietime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCookietimeBytes() {
      java.lang.Object ref = cookietime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cookietime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      tag_ = java.util.Collections.emptyList();
      cookietime_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(1, tag_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getCookietimeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tag_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCookietimeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Targeting.TargetingInfoList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.class, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.Builder.class);
      }

      // Construct using com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tagBuilder_.clear();
        }
        cookietime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.internal_static_Targeting_TargetingInfoList_descriptor;
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList getDefaultInstanceForType() {
        return com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.getDefaultInstance();
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList build() {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList buildPartial() {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList result = new com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cookietime_ = cookietime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList) {
          return mergeFrom((com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList other) {
        if (other == com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList.getDefaultInstance()) return this;
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        if (other.hasCookietime()) {
          bitField0_ |= 0x00000002;
          cookietime_ = other.cookietime_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Targeting.TargetingInfo tag = 1;
      private java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tag_ = new java.util.ArrayList<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo>(tag_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder> tagBuilder_;

      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder setTag(
          int index, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder setTag(
          int index, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder addTag(com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder addTag(
          int index, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder addTag(
          com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder addTag(
          int index, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<? extends com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          super.addAll(values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public java.util.List<? extends com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Targeting.TargetingInfo tag = 1;</code>
       */
      public java.util.List<com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfo.Builder, com.autohome.adrd.algo.protobuf.TargetingOperation.TargetingInfoOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }

      // optional string cookietime = 2;
      private java.lang.Object cookietime_ = "";
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public boolean hasCookietime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public java.lang.String getCookietime() {
        java.lang.Object ref = cookietime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cookietime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCookietimeBytes() {
        java.lang.Object ref = cookietime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cookietime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public Builder setCookietime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cookietime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public Builder clearCookietime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cookietime_ = getDefaultInstance().getCookietime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cookietime = 2;</code>
       */
      public Builder setCookietimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cookietime_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Targeting.TargetingInfoList)
    }

    static {
      defaultInstance = new TargetingInfoList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Targeting.TargetingInfoList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Targeting_TargetingInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Targeting_TargetingInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Targeting_TargetingInfoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Targeting_TargetingInfoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032targeting_sessionlog.proto\022\tTargeting\"" +
      "-\n\rTargetingInfo\022\r\n\005tagid\030\001 \001(\t\022\r\n\005score" +
      "\030\002 \001(\002\"N\n\021TargetingInfoList\022%\n\003tag\030\001 \003(\013" +
      "2\030.Targeting.TargetingInfo\022\022\n\ncookietime" +
      "\030\002 \001(\tB5\n\037com.autohome.adrd.algo.protobu" +
      "fB\022TargetingOperation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Targeting_TargetingInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Targeting_TargetingInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Targeting_TargetingInfo_descriptor,
              new java.lang.String[] { "Tagid", "Score", });
          internal_static_Targeting_TargetingInfoList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Targeting_TargetingInfoList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Targeting_TargetingInfoList_descriptor,
              new java.lang.String[] { "Tag", "Cookietime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
